name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v1.2.3)'
        required: true
        type: string
      changelog:
        description: 'Optional additional release notes'
        required: false
        type: string

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push --tags

  release:
    needs: prepare-release
    runs-on: ubuntu-latest

    environment:
      name: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/heads/main

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Set version
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> .env

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

  verify-linux-installer:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install atools
        run: curl https://raw.githubusercontent.com/arne-vl/atools/refs/heads/main/linux_installer.sh | sh

      - name: Verify Installation
        run: command -v atools
