name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v1.2.3)'
        required: true
        type: string
      changelog:
        description: 'Optional additional release notes'
        required: false
        type: string

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-cliff
        run: |
          GIT_CLIFF_LATEST_VERSION=$(curl -s https://api.github.com/repos/orhun/git-cliff/tags | grep "name" | sed -E 's/.*v([^"]+)".*/\1/' | head -n 1)
          curl -sSL https://github.com/orhun/git-cliff/releases/latest/download/git-cliff-${GIT_CLIFF_LATEST_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv git-cliff-${GIT_CLIFF_LATEST_VERSION}/git-cliff /usr/local/bin/git-cliff

      - name: Generate Changelog
        run: git-cliff -t ${{ github.event.inputs.version }} -o CHANGELOG.md

      - name: Commit Changelog & Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): ${{ github.event.inputs.version }}"
          git checkout -b release-${{ github.event.inputs.version }}  # Create a new release branch
          git push origin release-${{ github.event.inputs.version }}  # Push the release branch
          git push --tags

  release:
    needs: prepare-release
    runs-on: ubuntu-latest

    environment:
      name: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-linux-installer:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install atools
        run: curl https://raw.githubusercontent.com/arne-vl/atools/refs/heads/main/linux_installer.sh | sh

      - name: Verify Installation
        run: command -v atools
