name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify-linux-installer:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Install atools
        run: curl https://raw.githubusercontent.com/arne-vl/atools/refs/heads/main/linux_installer.sh | sh

      - name: Verify Installation
        run: command -v atools
