name: Verify Installers

on:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed

permissions:
  contents: read

jobs:
  verify-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64, 386]
    runs-on: ${{ matrix.os }}
    name: Verify linux ${{ matrix.arch }}
    environment: installers

    steps:
      - name: Install atools
        run: |
          curl https://raw.githubusercontent.com/arne-vl/atools/refs/heads/main/linux_installer.sh | sh
      - name: Verify installation
        run: |
          command -v atools
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify Versions
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/arne-vl/atools/tags | grep "name" | sed -E 's/.*v([^"]+)".*/\1/' | head -n 1)
          ATOOLS_VERSION=$(atools version | sed -n 's/.*: \([0-9.]*\)/\1/p')

          if echo $ATOOLS_VERSION | grep -q $LATEST_TAG; then
            echo "Version matches latest tag."
            echo "Latest Tag:" $LATEST_TAG
            echo "atools version:" $ATOOLS_VERSION
          else
            echo "Version does not match latest tag."
            echo "Latest Tag:" $LATEST_TAG
            echo "atools version:" $ATOOLS_VERSION
            exit 1
          fi
