name: Verify Installers

on:
  workflow_run:
    workflows: [Create Release]
    types:
      - completed

permissions:
  contents: read

jobs:
  verify-linux:
    runs-on: ubuntu-latest
    name: Verify linux

    steps:
      - name: Install atools
        run: |
          curl https://raw.githubusercontent.com/avl-systems/atools/refs/heads/main/linux_installer.sh | sh

      - name: Verify installation
        run: |
          command -v atools

      - name: Verify Versions
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/avl-systems/atools/tags | grep '"name":' | sed -E 's/.*"v?([^"]+)".*/\1/' | sort -Vr | head -n 1)
          ATOOLS_VERSION=$(atools version | sed -n 's/.*: \([0-9.]*\)/\1/p')

          if echo $ATOOLS_VERSION | grep -q $LATEST_TAG; then
            echo "Version matches latest tag."
            echo "Latest Tag:" $LATEST_TAG
            echo "atools version:" $ATOOLS_VERSION
          else
            echo "Version does not match latest tag."
            echo "Latest Tag:" $LATEST_TAG
            echo "atools version:" $ATOOLS_VERSION
            exit 1
          fi
